export const GET_GUESTS_START = "GET_GUESTS_START";
export const GET_GUESTS_SUCCESS = "GET_GUESTS_SUCCESS";
export const GET_GUESTS_FAIL = "GET_GUESTS_FAIL";
export const CLEAN_GUESTS = "CLEAN_GUESTS";

export const GET_GUEST_BY_ID_START = "GET_GUEST_BY_ID_START";
export const GET_GUEST_BY_ID_SUCCESS = "GET_GUEST_BY_ID_SUCCESS";
export const GET_GUEST_BY_ID_FAIL = "GET_GUEST_BY_ID_FAIL";
export const CLEAN_GUEST = "CLEAN_GUEST";

export const EDIT_GUEST_BY_ID_START = "EDIT_GUEST_BY_ID_START";
export const EDIT_GUEST_BY_ID_SUCCESS = "EDIT_GUEST_BY_ID_SUCCESS";
export const EDIT_GUEST_BY_ID_FAIL = "EDIT_GUEST_BY_ID_FAIL";

export const DELETE_GUEST_BY_ID_START = "DELETE_GUEST_BY_ID_START";
export const DELETE_GUEST_BY_ID_SUCCESS = "DELETE_GUEST_BY_ID_SUCCESS";
export const DELETE_GUEST_BY_ID_FAIL = "DELETE_GUEST_BY_ID_FAIL";

export const ADD_GUEST_START = "ADD_GUEST_START";
export const ADD_GUEST_SUCCESS = "ADD_GUEST_SUCCESS";
export const ADD_GUEST_FAIL = "ADD_GUEST_FAIL";

export const SET_GUEST_TABLE_START = "SET_GUEST_TABLE_START";
export const SET_GUEST_TABLE_SUCCESS = "SET_GUEST_TABLE_SUCCESS";
export const SET_GUEST_TABLE_FAIL = "SET_GUEST_TABLE_FAIL";

