export const LOAD_TABLES_START = 'LOAD_TABLES_START';
export const LOAD_TABLES_SUCCESS = 'LOAD_TABLES_SUCCESS';
export const LOAD_TABLES_FAIL = 'LOAD_TABLES_FAILED';
export const CLEAN_TABLES = 'CLEAN_TABLES';
