export const ELECTIONS_START = 'ELECTIONS_START';
export const ELECTIONS_SUCCESS = 'ELECTIONS_SUCCESS';
export const ELECTIONS_FAIL = 'ELECTIONS_FAILED';
export const CLEAN_ELECTIONS = 'CLEAN_ELECTIONS';