export const ELECTIONS_START = 'ELECTIONS_START';
export const ELECTIONS_SUCCESS = 'ELECTIONS_SUCCESS';
export const ELECTIONS_FAIL = 'ELECTIONS_FAILED';
export const CLEAN_ELECTIONS = 'CLEAN_ELECTIONS';

export const UPDATE_USERS_TO_ELECTIONS_SUCCESS = 'UPDATE_USERS_TO_ELECTIONS_SUCCESS';

export const RESULTS = 'RESULTS';


export const GET_USERS_TO_ELECTIONS_START = 'GET_USERS_TO_ELECTIONS_START';
export const GET_USERS_TO_ELECTIONS_SUCCESS = 'GET_USERS_TO_ELECTIONS_SUCCESS';
export const GET_USERS_TO_ELECTIONS_FAIL = 'GET_USERS_TO_ELECTIONS_FAILED';
