export const GET_USERS_START = "GET_USERS_START";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const CLEAN_USERS = "CLEAN_USERS";

export const GET_USER_BY_ID_START = "GET_USER_BY_ID_START";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAIL = "GET_USER_BY_ID_FAIL";
export const CLEAN_USER = "CLEAN_USER";

export const EDIT_USER_BY_ID_START = "EDIT_USER_BY_ID_START";
export const EDIT_USER_BY_ID_SUCCESS = "EDIT_USER_BY_ID_SUCCESS";
export const EDIT_USER_BY_ID_FAIL = "EDIT_USER_BY_ID_FAIL";

export const DELETE_USER_BY_ID_START = "DELETE_USER_BY_ID_START";
export const DELETE_USER_BY_ID_SUCCESS = "DELETE_USER_BY_ID_SUCCESS";
export const DELETE_USER_BY_ID_FAIL = "DELETE_USER_BY_ID_FAIL";

export const ADD_USER_START = "ADD_USER_START";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";