// export const AUTH_START = 'AUTH_START';
// export const AUTH_SUCCESS = 'AUTH_SUCCESS';
// export const AUTH_FAILED = 'AUTH_FAILED';
// export const AUTH_USER_INFO_START = 'AUTH_USER_INFO_START'
// export const AUTH_USER_INFO_SUCCESS = 'AUTH_USER_INFO_SUCCESS'
// export const AUTH_LOGIN = 'AUTH_LOGIN';
// export const AUTH_LOGOUT = 'AUTH_LOGOUT';
// export const AUTH_START_LOGOUT = 'AUTH_START_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const CHECK_AUTH_START = "CHECK_AUTH_START";
export const CHECK_AUTH_SUCCESS = "CHECK_AUTH_SUCCESS";
export const CHECK_AUTH_FAIL = "CHECK_AUTH_FAIL";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SPECIFIC_START = "LOGOUT_SPECIFIC_START";
export const LOGOUT_SPECIFIC_SUCCESS = "LOGOUT_SPECIFIC_SUCCESS";
export const LOGOUT_SPECIFIC_FAIL = "LOGOUT_SPECIFIC_FAIL";

export const LOGOUT_ALL_START = "LOGOUT_ALL_START";
export const LOGOUT_ALL_SUCCESS = "LOGOUT_ALL_SUCCESS";
export const LOGOUT_ALL_FAIL = "LOGOUT_ALL_FAIL";

