export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_USER_INFO_START = 'AUTH_USER_INFO_START'
export const AUTH_USER_INFO_SUCCESS = 'AUTH_USER_INFO_SUCCESS'
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_START_LOGOUT = 'AUTH_START_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';



export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const PRODUCT_ACTION_START = "PRODUCT_ACTION_START";
export const PRODUCT_ACTION_SUCCESS = "PRODUCT_ACTION_SUCCESS";
export const PRODUCT_ACTION_FAIL = "PRODUCT_ACTION_FAIL";

export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";


