export const PRODUCT_ACTION_START = "PRODUCT_ACTION_START";
export const PRODUCT_ACTION_SUCCESS = "PRODUCT_ACTION_SUCCESS";
export const PRODUCT_ACTION_FAIL = "PRODUCT_ACTION_FAIL";


export const CHECK_FOR_UPDATES_START = "CHECK_FOR_UPDATES_START";
export const CHECK_FOR_UPDATES_SUCCESS = "CHECK_FOR_UPDATES_SUCCESS";
export const CHECK_FOR_UPDATES_FAIL = "CHECK_FOR_UPDATES_FAIL";