export const GET_CLIENTS_START = "GET_CLIENTS_START";
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS";
export const GET_CLIENTS_FAIL = "GET_CLIENTS_FAIL";
export const CLEAN_CLIENTS = "CLEAN_CLIENTS";

export const GET_CLIENT_BY_ID_START = "GET_CLIENT_BY_ID_START";
export const GET_CLIENT_BY_ID_SUCCESS = "GET_CLIENT_BY_ID_SUCCESS";
export const GET_CLIENT_BY_ID_FAIL = "GET_CLIENT_BY_ID_FAIL";
export const CLEAN_CLIENT = "CLEAN_CLIENT";

export const EDIT_CLIENT_BY_ID_START = "EDIT_CLIENT_BY_ID_START";
export const EDIT_CLIENT_BY_ID_SUCCESS = "EDIT_CLIENT_BY_ID_SUCCESS";
export const EDIT_CLIENT_BY_ID_FAIL = "EDIT_CLIENT_BY_ID_FAIL";

export const DELETE_CLIENT_BY_ID_START = "DELETE_CLIENT_BY_ID_START";
export const DELETE_CLIENT_BY_ID_SUCCESS = "DELETE_CLIENT_BY_ID_SUCCESS";
export const DELETE_CLIENT_BY_ID_FAIL = "DELETE_CLIENT_BY_ID_FAIL";

export const ADD_CLIENT_START = "ADD_CLIENT_START";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_FAIL = "ADD_CLIENT_FAIL";